version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"   # host:container
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: risk_predictionDB
      POSTGRES_USER: abdullah
      POSTGRES_PASSWORD: abdullah123

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8080:8080"


# To run the services, use the command:
# docker-compose up -d

# Access Adminer at: http://localhost:8080
# Database connection details for Adminer:
# System: PostgreSQL
# Server: db
# Username: abdullah
# Password: abdullah123
# Database: risk_predictionDB

# To stop the services, use the command:
# docker-compose down